Feature/add new schedule item
Somfic/1.3-SchoolPlanner pull request #71
Opened 2022-04-05 15:35 UTC by OwenArts

Completed overlapping detection within schedule.
Overlapping subjects, teachers, hours, student groups etc.

Removed nullpointer from adding new teacher or subject.
Configed DropDown to prevent nullpointer
Merged with MultipleTeachers and removed the errors that ocured by the merge conflicts

2022-04-05 16:59 UTC, Somfic requested changes

2022-04-05 16:59 UTC, Somfic commented on src/data/Classroom.java
> -    public Classroom() {
Deze lege constructor is nodig voor de import met JSON

2022-04-05 16:59 UTC, Somfic commented on src/data/Lesson.java
> -    public Lesson() {
Deze lege constructor is nodig voor de import met JSON

2022-04-05 16:59 UTC, Somfic commented on src/data/Person.java
> -    public Person() {
Deze lege constructor is nodig voor de import met JSON

2022-04-05 16:59 UTC, Somfic commented on src/data/Student.java
> -    public Student() {
Deze lege constructor is nodig voor de import met JSON

2022-04-05 16:59 UTC, Somfic commented on src/data/StudentGroup.java
> -	public StudentGroup() {
Deze lege constructor is nodig voor de import met JSON

2022-04-05 16:59 UTC, Somfic commented on src/data/Teacher.java
> -    public Teacher() {
Deze lege constructor is nodig voor de import met JSON

2022-04-05 17:24 UTC, OwenArts commented
Heb overal een empty constructor toegevoegd

2022-04-06 07:23 UTC, Somfic approved these changes

2022-04-06 07:23 UTC, merged